name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --name ModpackDownloader main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ModpackDownloader-${{ matrix.os }}
          path: dist/ModpackDownloader${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ModpackDownloader-ubuntu-latest
          path: ./release-artifacts/ubuntu

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ModpackDownloader-macos-latest
          path: ./release-artifacts/macos

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ModpackDownloader-windows-latest
          path: ./release-artifacts/windows

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release-artifacts/ubuntu/ModpackDownloader
            ./release-artifacts/macos/ModpackDownloader
            ./release-artifacts/windows/ModpackDownloader.exe
